# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 19:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=games.models.default_board),
        ),
        migrations.AddField(
            model_name='game',
            name='can_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
    ]
