# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cols',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='rows',
            field=models.IntegerField(default=6),
        ),
    ]
