# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20180423_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
