# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instances',
            field=models.ManyToManyField(related_name='games', to='instances.Instance'),
        ),
    ]
