# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170831_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='total_players',
            new_name='max_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rows',
        ),
        migrations.AddField(
            model_name='game',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=games.models.default_history),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_player', to='players.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='players.Player'),
        ),
    ]
